ControlFocus("Open","","Edit1")
Sleep(3000)
ControlSetText("Open","","Edit1","C:\Users\Solomon\git\SeleniumJavaFullFramework\FullSeleniumFramework\AutoIT\FileTest1.txt")
Sleep(3000)
ControlClick("Open","","Button1")
